// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe-e63EOLAUsRR4BhhuirbqUgsv29RCaI',
    appId: '1:778946389532:web:f33b6b48ec54cd19c721d9',
    messagingSenderId: '778946389532',
    projectId: 'recordmed-a7c06',
    authDomain: 'recordmed-a7c06.firebaseapp.com',
    databaseURL: 'https://recordmed-a7c06-default-rtdb.firebaseio.com',
    storageBucket: 'recordmed-a7c06.appspot.com',
    measurementId: 'G-F4S5ZSWH47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE-dcTYCgA_qoeCBSpMxCiOg9gl0CRGD0',
    appId: '1:778946389532:android:335a8c0416457af0c721d9',
    messagingSenderId: '778946389532',
    projectId: 'recordmed-a7c06',
    databaseURL: 'https://recordmed-a7c06-default-rtdb.firebaseio.com',
    storageBucket: 'recordmed-a7c06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHpEzXGIaIwaNvSGDvsvPmYxKvm4IBIIA',
    appId: '1:778946389532:ios:dc77092a22692efac721d9',
    messagingSenderId: '778946389532',
    projectId: 'recordmed-a7c06',
    databaseURL: 'https://recordmed-a7c06-default-rtdb.firebaseio.com',
    storageBucket: 'recordmed-a7c06.appspot.com',
    iosClientId: '778946389532-skhkbiisvi99mh8j8k5nbc6cngi0kn56.apps.googleusercontent.com',
    iosBundleId: 'com.example.app5',
  );
}
